### ISSUE TITLE
It seems like Voice Activity Detection (VAD) isn't working very accurately?

### ISSUE THREAD

**Issue by ITHealer** [vilassn/whisper_android#3]
https://github.com/vilassn/whisper_android/blob/master/app/src/main/cpp/vad.cpp

![image](https://github.com/vilassn/whisper_android/assets/94621494/8b4590db-b821-48a7-8679-c1b98989bc3e)

I tried it with sample rate 16000 and 44100 but both results were "Silence".

Do I need to adjust any parameters to suit different audio files?

Thanks!

**Comment by vilassn** [comment]
Can you check with silent_detection.cpp implementation?

**Comment by ITHealer** [comment]
> Can you check with silent_detection.cpp implementation?
> 
> VAD feature is under implementation.

Is there anything new?
