### ISSUE TITLE
Is it possible to set input language with whisper-base.tflite with this code

### ISSUE THREAD

**Issue by SchweitzerGAO** [vilassn/whisper_android#6]
Here's the thing, I speak Chinese but the result is in English with similar meaning. So I am wondering if it is possible to set the input language so that the output will be in the same language as the input.

**Comment by YangMing6401** [comment]
@SchweitzerGAO Hello! May I ask you about the language? How did you do to set the input language , so that the output will be in the same language as input?

**Comment by vilassn** [comment]
@YangMing6401 Does apk shared in release directory work on your device?

**Comment by YangMing6401** [comment]
@vilassn Yes, it can work on my device
And I want to ask you that Is it possible to set input or output languages?
